/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.javaagent.instrumentation.spring.gateway.common;

import io.opentelemetry.api.common.AttributeKey;
import io.opentelemetry.javaagent.bootstrap.internal.AgentInstrumentationConfig;
import java.util.regex.Pattern;
import javax.annotation.Nullable;

/**
 * Shared helper class for Spring Cloud Gateway instrumentation across different versions (WebFlux
 * and WebMVC).
 */
public final class GatewayRouteHelper {

  /** Route ID attribute key. */
  public static final AttributeKey<String> ROUTE_ID_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.id");

  /** Route URI attribute key. */
  public static final AttributeKey<String> ROUTE_URI_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.uri");

  /** Route order attribute key. */
  public static final AttributeKey<Long> ROUTE_ORDER_ATTRIBUTE =
      AttributeKey.longKey("spring-cloud-gateway.route.order");

  /** Route filter size attribute key. */
  public static final AttributeKey<Long> ROUTE_FILTER_SIZE_ATTRIBUTE =
      AttributeKey.longKey("spring-cloud-gateway.route.filter.size");

  /**
   * Uses the matched path predicate pattern (e.g. {@code /api/users/**}) for {@code http.route}.
   */
  public static final String HTTP_ROUTE_FORMAT_PATH_PATTERN = "path-pattern";

  private static final boolean CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;
  private static final boolean USE_PATH_PATTERN_FOR_HTTP_ROUTE;

  static {
    CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES =
        AgentInstrumentationConfig.get()
            .getBoolean(
                "otel.instrumentation.spring-cloud-gateway.experimental-span-attributes", false);
    String httpRouteFormat =
        AgentInstrumentationConfig.get()
            .getString(
                "otel.instrumentation.spring-cloud-gateway.http-route-format",
                HTTP_ROUTE_FORMAT_PATH_PATTERN);
    USE_PATH_PATTERN_FOR_HTTP_ROUTE = HTTP_ROUTE_FORMAT_PATH_PATTERN.equals(httpRouteFormat);
  }

  /* Regex for UUID */
  private static final Pattern UUID_REGEX =
      Pattern.compile(
          "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

  private static final String INVALID_RANDOM_ROUTE_ID =
      "org.springframework.util.AlternativeJdkIdGenerator@";

  private GatewayRouteHelper() {}

  /** Returns whether experimental span attributes should be captured. */
  public static boolean shouldCaptureExperimentalSpanAttributes() {
    return CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;
  }

  /** Returns whether {@code http.route} should use the matched path predicate pattern. */
  public static boolean usePathPatternForHttpRoute() {
    return USE_PATH_PATTERN_FOR_HTTP_ROUTE;
  }

  /**
   * To avoid high cardinality, we ignore random UUID generated by Spring Cloud Gateway. Spring
   * Cloud Gateway generates invalid random routeID, and it is fixed until 3.1.x
   *
   * @see <a
   *     href="https://github.com/spring-cloud/spring-cloud-gateway/commit/5002fe2e0a2825ef47dd667cade37b844c276cf6">Spring
   *     Cloud Gateway commit</a>
   */
  @Nullable
  public static String convergeRouteId(@Nullable String routeId) {
    if (routeId == null || routeId.isEmpty()) {
      return null;
    }
    if (UUID_REGEX.matcher(routeId).matches()) {
      return null;
    }
    if (routeId.startsWith(INVALID_RANDOM_ROUTE_ID)) {
      return null;
    }
    return routeId;
  }
}
